version: "3.7"
services:
  azdoagent:
    image: dockeragent:latest
    container_name: azdoagent
    networks:
      - azdo_agents_network
    environment:
      - AZP_URL=$AZP_URL
      - AZP_TOKEN=$AZP_TOKEN
      - AZP_AGENT_NAME=$AZP_AGENT_NAME
      - AZP_POOL=$AZP_POOL
    restart: unless-stopped

networks:
  azdo_agents_network:
    external: true

